// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dutwhznfxzeeywbmlshb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1dHdoem5meHplZXl3Ym1sc2hiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyODAyOTYsImV4cCI6MjA1ODg1NjI5Nn0.kp96Wjgih1SGGMTNOJyLzmyX-t5yj_fRX_6gCzB-lHo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);